apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume-0
  labels:
    app: postgres-app
spec:
  storageClassName: psql-manual
  claimRef:
    name: data-postgres-0
    namespace: psql-dev
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgres/postgres0

