kind: Service
apiVersion: v1
metadata:
  name: spark
  namespace: spark-dev
spec:
  type: LoadBalancer
  ports:
    - name: webui
      port: 8080
      targetPort: 8080
    - name: spark-master
      port: 7077
      targetPort: 7077
    - name: spark-appl
      port: 4040
      targetPort: 4040      
    - name: jupyter
      port: 8888
      targetPort: 8888
  selector:
    app: spark
    

      
