apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-volume
spec:
  storageClassName: spark-manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/spark-notebooks
