apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-jupyter
  namespace: spark-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-jupyter
  template:
    metadata:
      labels:
        app: spark-jupyter
    spec:
      serviceAccountName: spark
      containers:
      - name: spark-jupyter
        image: spark-jupyter:3.5.8
        imagePullPolicy: Never
        command: ["jupyter"]
        args:
          - lab
          - "--ip=0.0.0.0"
          - "--no-browser"
          - "--allow-root"
          - "--NotebookApp.token=''"
          - "--NotebookApp.password=''"
        ports:
        - containerPort: 8888
        - containerPort: 8080
        - containerPort: 7077
        - containerPort: 4040
        volumeMounts:
          - name: spark-storage
            mountPath: /workspace   # Jupyter default notebook directory
        env:
          - name: AWS_ACCESS_KEY_ID
            value: "minio"
          - name: AWS_SECRET_ACCESS_KEY
            value: "minio123"
          - name: AWS_DEFAULT_REGION
            value: "us-east-1"
          - name: AWS_REGION
            value: "us-east-1"
      volumes:
        - name: spark-storage
          persistentVolumeClaim:
            claimName: data-spark            
            
