apiVersion: v1
kind: Service
metadata:
  name: dremio-service
  namespace: dremio-dev
spec:
  type: LoadBalancer
  selector:
    app: dremio
  ports:
    - name: web-ui
      port: 9047
      targetPort: 9047
    - name: jdbc
      port: 31010
      targetPort: 31010
    - name: flight
      port: 32010
      targetPort: 32010
